"use client";

import { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {
  FileText,
  Printer,
  Download,
  X,
  ShieldCheck,
  CheckCircle2,
  Building2,
  Calendar,
  Layers,
  Sparkles,
} from "lucide-react";
import { toast } from "sonner";
import { downloadBlob } from "@/lib/api/client";
import type { HeiApprovedRecord, HeiApprovedResponse } from "@/lib/api/types";
import { cn } from "@/lib/utils/cn";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  institution: string;
  reviewerName: string;
  data: HeiApprovedResponse | undefined;
}

export function DecisionExportModal({
  open,
  onOpenChange,
  institution,
  reviewerName,
  data,
}: Props) {
  const [downloading, setDownloading] = useState(false);

  if (!data) return null;

  const items = data.items;
  const stats = data.stats;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    try {
      setDownloading(true);
      const manifest = {
        title: "EduPathAI Board of Studies Decision Ledger Export",
        institution,
        exportedBy: reviewerName,
        exportedAt: new Date().toISOString(),
        framework: "UGC ABC / National Credit Framework (NCrF) NEP 2020",
        privacyCompliance: "DPDP Act (2023) Zero-PII Standard",
        statistics: {
          totalDecisions: items.length,
          approvalRate: `${Math.round(stats.approvalRate * 100)}%`,
          approvedThisWeek: stats.approvedThisWeek,
          rejectedThisWeek: stats.rejectedThisWeek,
          contestedThisWeek: stats.escalatedThisWeek,
          avgReviewDuration: stats.avgReviewDuration,
        },
        decisions: items.map((it) => ({
          decisionId: it.decisionId,
          studentName: it.studentName,
          programme: it.studentProgramme,
          sourceInstitution: it.sourceInstitution,
          targetInstitution: it.targetInstitution,
          courses: it.courses,
          outcome: it.outcome,
          bridgeRequired: it.bridgeRequired,
          reviewer: it.reviewer,
          reviewDuration: it.reviewDuration,
          decidedAt: it.decidedAt,
          currentHash: it.currentHash ?? null,
          previousHash: it.previousHash ?? null,
        })),
      };

      const jsonStr = JSON.stringify(manifest, null, 2);
      const blob = new Blob([jsonStr], { type: "application/json" });
      downloadBlob(blob, `EduPathAI-DecisionLedger-${institution.replace(/\s+/g, "_")}-${new Date().toISOString().slice(0, 10)}.json`);
      toast.success("Verifiable JSON audit manifest exported");
    } catch {
      toast.error("Failed to generate export file");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 z-50 bg-slate-950/65 backdrop-blur-md transition-opacity" />
        <Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[92vh] w-[95vw] max-w-4xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-3xl border border-slate-200/80 bg-white p-6 shadow-2xl focus:outline-none md:p-8">
          {/* Header */}
          <div className="flex items-start justify-between gap-4 border-b border-slate-200 pb-5">
            <div className="flex items-center gap-3">
              <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[rgb(26_42_82)] text-white shadow-md shadow-navy-950/20">
                <FileText className="h-6 w-6" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <Dialog.Title className="font-display text-[20px] font-bold text-[rgb(26_42_82)]">
                    Board of Studies Audit Manifest
                  </Dialog.Title>
                  <span className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-emerald-800 border border-emerald-300">
                    Official Record
                  </span>
                </div>
                <Dialog.Description className="mt-0.5 text-[12px] text-text-secondary">
                  Complete hash-chained decision ledger for {institution} · Generated by {reviewerName}
                </Dialog.Description>
              </div>
            </div>

            <Dialog.Close asChild>
              <button
                type="button"
                className="rounded-full p-2 text-text-muted hover:bg-slate-100 hover:text-text-primary transition-colors"
                aria-label="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </Dialog.Close>
          </div>

          {/* Executive Stats Summary */}
          <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4">
              <span className="text-[10.5px] font-bold uppercase tracking-wider text-text-muted">Total Decisions</span>
              <p className="mt-1 font-display text-[26px] font-bold text-text-primary">{items.length}</p>
            </div>
            <div className="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4">
              <span className="text-[10.5px] font-bold uppercase tracking-wider text-emerald-800">Approval Rate</span>
              <p className="mt-1 font-display text-[26px] font-bold text-emerald-700">
                {Math.round(stats.approvalRate * 100)}%
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4">
              <span className="text-[10.5px] font-bold uppercase tracking-wider text-text-muted">Avg Turnaround</span>
              <p className="mt-1 font-display text-[22px] font-bold text-text-primary">{stats.avgReviewDuration}</p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4">
              <span className="text-[10.5px] font-bold uppercase tracking-wider text-text-muted">Contested / Flagged</span>
              <p className="mt-1 font-display text-[26px] font-bold text-amber-700">{stats.escalatedThisWeek}</p>
            </div>
          </div>

          {/* Statutory Declaration Banner */}
          <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50/80 p-3.5 text-[11.5px] text-text-secondary flex items-start gap-2.5">
            <ShieldCheck className="h-4 w-4 text-emerald-700 shrink-0 mt-0.5" />
            <p className="leading-relaxed">
              <strong>Statutory Compliance:</strong> This audit ledger export is certified by the Board of Studies at {institution} in accordance with UGC Academic Bank of Credits (ABC) regulations and National Credit Framework (NCrF) credit transfer mandates under NEP 2020.
            </p>
          </div>

          {/* Decisions Table Preview */}
          <div className="mt-5 rounded-2xl border border-slate-200 overflow-hidden">
            <div className="max-h-[320px] overflow-y-auto">
              <table className="w-full text-left text-[12px]">
                <thead className="sticky top-0 bg-slate-100/90 backdrop-blur-xs text-[10.5px] font-bold uppercase tracking-wider text-text-muted border-b border-slate-200">
                  <tr>
                    <th className="py-2.5 px-3">Date</th>
                    <th className="py-2.5 px-3">Candidate</th>
                    <th className="py-2.5 px-3">Origin HEI</th>
                    <th className="py-2.5 px-3">Courses</th>
                    <th className="py-2.5 px-3">Reviewer</th>
                    <th className="py-2.5 px-3 text-right">Outcome</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 font-sans">
                  {items.map((it) => (
                    <tr key={it.id} className="hover:bg-slate-50/80 transition-colors">
                      <td className="py-2.5 px-3 font-mono text-[11px] text-text-muted whitespace-nowrap">
                        {new Date(it.decidedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short" })}
                      </td>
                      <td className="py-2.5 px-3">
                        <span className="font-semibold text-text-primary block">{it.studentName}</span>
                        <span className="text-[10.5px] text-text-muted">{it.studentProgramme}</span>
                      </td>
                      <td className="py-2.5 px-3 text-text-secondary">{it.sourceInstitution}</td>
                      <td className="py-2.5 px-3 font-mono text-[11px] text-text-primary">{it.courses}</td>
                      <td className="py-2.5 px-3 text-text-secondary text-[11px]">{it.reviewer}</td>
                      <td className="py-2.5 px-3 text-right">
                        <span
                          className={cn(
                            "inline-block rounded-full px-2 py-0.5 text-[9.5px] font-bold uppercase tracking-wider",
                            it.outcome === "APPROVED"
                              ? "bg-emerald-100 text-emerald-800"
                              : it.outcome === "CONTESTED"
                              ? "bg-amber-100 text-amber-900"
                              : "bg-rose-100 text-rose-800"
                          )}
                        >
                          {it.outcome}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Action Footer */}
          <div className="mt-6 flex flex-col-reverse sm:flex-row items-center justify-between gap-3 pt-4 border-t border-slate-200">
            <span className="text-[11.5px] text-text-muted">
              {items.length} records verified on SHA-256 hash-chained ledger
            </span>

            <div className="flex items-center gap-2.5 w-full sm:w-auto">
              <button
                type="button"
                onClick={() => onOpenChange(false)}
                className="flex-1 sm:flex-initial rounded-xl border border-slate-200 px-4 py-2.5 text-[12.5px] font-semibold text-text-secondary hover:bg-slate-50 transition-colors"
              >
                Close
              </button>
              <button
                type="button"
                onClick={handlePrint}
                className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-[12.5px] font-semibold text-text-primary hover:bg-slate-50 shadow-xs transition-colors"
              >
                <Printer className="h-4 w-4 text-text-muted" />
                <span>Print Manifest</span>
              </button>
              <button
                type="button"
                onClick={handleDownloadJson}
                disabled={downloading}
                className="flex-1 sm:flex-initial inline-flex items-center justify-center gap-2 rounded-xl bg-[rgb(26_42_82)] px-4 py-2.5 text-[12.5px] font-semibold text-white shadow-md shadow-navy-950/20 hover:bg-[rgb(34_54_104)] disabled:opacity-50 transition-all"
              >
                <Download className="h-4 w-4" />
                <span>{downloading ? "Exporting…" : "Export JSON"}</span>
              </button>
            </div>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
